# Generated by Django 6.0.3 on 2026-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('net_weight', models.FloatField()),
                ('multiplicity', models.IntegerField()),
                ('packaging', models.CharField(max_length=100)),
                ('composition', models.TextField()),
                ('protein_100', models.FloatField()),
                ('fat_100', models.FloatField()),
                ('carbs_100', models.FloatField()),
                ('kcal_100', models.FloatField()),
                ('kj_100', models.FloatField()),
                ('protein_portion', models.FloatField()),
                ('fat_portion', models.FloatField()),
                ('carbs_portion', models.FloatField()),
                ('kcal_portion', models.FloatField()),
                ('kj_portion', models.FloatField()),
            ],
        ),
    ]
