# Generated by Django 6.0.3 on 2026-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbs_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbs_portion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat_portion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kcal_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kcal_portion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kj_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kj_portion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protein_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protein_portion',
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Углеводы на 1 порц.'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жиры на 1 порц.'),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal_per_100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ккал на 100г'),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ккал на 1 порц.'),
        ),
        migrations.AddField(
            model_name='product',
            name='kj_per_100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='КДж на 100г'),
        ),
        migrations.AddField(
            model_name='product',
            name='kj_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='КДж на 1 порц.'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасовка'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Белки на 1 порц.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplicity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кратность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Масса нетто (одной ед., г)'),
        ),
    ]
