# Generated by Django 6.0.3 on 2026-04-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_options_remove_product_carbs_100_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='multiplicity',
        ),
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кратность / Фасовка'),
        ),
    ]
