# Generated by Django 6.0.3 on 2026-04-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_multiplicity_alter_product_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs_per_serving',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Углеводы на 1 порц.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_per_serving',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Жиры на 1 порц.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal_per_100',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Ккал на 100г'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal_per_serving',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Ккал на 1 порц.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kj_per_100',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='КДж на 100г'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kj_per_serving',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='КДж на 1 порц.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Масса нетто (одной ед., г)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein_per_serving',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Белки на 1 порц.'),
        ),
    ]
