# Generated by Django 6.0.3 on 2026-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_carbs_alter_product_carbs_per_serving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Масса нетто (одной ед., г)'),
        ),
    ]
