# Generated by Django 6.0.3 on 2026-04-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_allergen_product_cost_product_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название рациона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('kcal_category', models.IntegerField(choices=[(1200, '1200 ккал'), (1500, '1500 ккал'), (1800, '1800 ккал'), (2500, '2500 ккал')], verbose_name='Категория калорийности')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рацион',
                'verbose_name_plural': 'Рационы',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('breakfast_250', 'Завтрак 250–350 ккал'), ('breakfast_400', 'Завтрак 400–500 ккал'), ('second_400', 'Второе 400–500 ккал'), ('second_500', 'Второе 500–600 ккал'), ('soup_200', 'Суп 200 ккал'), ('soup_300', 'Суп 300 ккал'), ('salad_150', 'Салат 150–250 ккал'), ('salad_250', 'Салат 250–350 ккал'), ('dessert_100', 'Выпечка/Десерт 100–250 ккал'), ('dessert_300', 'Выпечка/Десерт 300–350 ккал'), ('smoothie', 'Смузи 100–150 ккал'), ('sandwich', 'Сэндвич 300–350 ккал')], max_length=50, verbose_name='Тип приёма пищи')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ration_slots', to='myapp.product', verbose_name='Блюдо')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='myapp.ration', verbose_name='Рацион')),
            ],
            options={
                'verbose_name': 'Слот рациона',
                'verbose_name_plural': 'Слоты рациона',
                'ordering': ['order'],
            },
        ),
    ]
