# Generated by Django 6.0.3 on 2026-04-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_ration_rationslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('breakfast_250', 'Завтрак 250–350 ккал'), ('breakfast_400', 'Завтрак 400–500 ккал'), ('second_400', 'Второе 400–500 ккал'), ('second_500', 'Второе 500–600 ккал'), ('soup_200', 'Суп 200 ккал'), ('soup_300', 'Суп 300 ккал'), ('salad_150', 'Салат 150–250 ккал'), ('salad_250', 'Салат 250–350 ккал'), ('dessert_100', 'Выпечка/Десерт 100–250 ккал'), ('dessert_300', 'Выпечка/Десерт 300–350 ккал'), ('smoothie', 'Смузи 100–150 ккал'), ('sandwich', 'Сэндвич 300–350 ккал')], max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа рационов',
                'verbose_name_plural': 'Группы рационов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='rationslot',
            name='slot_type',
            field=models.CharField(choices=[('breakfast_250', 'Завтрак 250–350 ккал'), ('breakfast_400', 'Завтрак 400–500 ккал'), ('second_400', 'Второе 400–500 ккал'), ('second_500', 'Второе 500–600 ккал'), ('soup_200', 'Суп 200 ккал'), ('soup_300', 'Суп 300 ккал'), ('salad_150', 'Салат 150–250 ккал'), ('salad_250', 'Салат 250–350 ккал'), ('dessert_100', 'Выпечка/Десерт 100–250 ккал'), ('dessert_300', 'Выпечка/Десерт 300–350 ккал'), ('smoothie', 'Смузи 100–150 ккал'), ('sandwich', 'Сэндвич 300–350 ккал')], max_length=50, verbose_name='Категория блюда'),
        ),
        migrations.AddField(
            model_name='product',
            name='meal_categories',
            field=models.ManyToManyField(blank=True, help_text='К каким приёмам пищи подходит это блюдо', to='myapp.mealcategory', verbose_name='Категории блюда'),
        ),
        migrations.AddField(
            model_name='ration',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rations', to='myapp.rationgroup', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
