# Generated by Django 6.0.3 on 2026-04-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mealcategory_rationgroup_alter_rationslot_slot_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='meal_categories',
            field=models.ManyToManyField(blank=True, help_text='К каким приёмам пищи относится это блюдо', to='myapp.mealcategory', verbose_name='Категории блюда'),
        ),
        migrations.AlterField(
            model_name='ration',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rations', to='myapp.rationgroup', verbose_name='Группа'),
        ),
    ]
