# Generated by Django 6.0.3 on 2026-04-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_product_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal_category', models.IntegerField(choices=[(1200, '1200 ккал'), (1500, '1500 ккал'), (1800, '1800 ккал'), (2500, '2500 ккал')], unique=True, verbose_name='Категория калорийности')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон рациона',
                'verbose_name_plural': 'Шаблоны рационов',
                'ordering': ['kcal_category'],
            },
        ),
        migrations.AlterModelOptions(
            name='ration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рацион', 'verbose_name_plural': 'Рационы'},
        ),
        migrations.RemoveField(
            model_name='ration',
            name='date',
        ),
        migrations.AlterField(
            model_name='product',
            name='meal_categories',
            field=models.ManyToManyField(blank=True, to='myapp.mealcategory', verbose_name='Категории блюда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Масса нетто (г)'),
        ),
        migrations.CreateModel(
            name='RationTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('breakfast_250', 'Завтрак 250–350 ккал'), ('breakfast_400', 'Завтрак 400–500 ккал'), ('second_400', 'Второе 400–500 ккал'), ('second_500', 'Второе 500–600 ккал'), ('soup_200', 'Суп 200 ккал'), ('soup_300', 'Суп 300 ккал'), ('salad_150', 'Салат 150–250 ккал'), ('salad_250', 'Салат 250–350 ккал'), ('dessert_100', 'Выпечка/Десерт 100–250 ккал'), ('dessert_300', 'Выпечка/Десерт 300–350 ккал'), ('smoothie', 'Смузи 100–150 ккал'), ('sandwich', 'Сэндвич 300–350 ккал')], max_length=50, verbose_name='Тип слота')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='myapp.rationtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Слот шаблона',
                'verbose_name_plural': 'Слоты шаблона',
                'ordering': ['order'],
            },
        ),
    ]
