# Generated by Django 6.0.3 on 2026-04-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rationtemplate_alter_ration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iiko_category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория iiko'),
        ),
        migrations.AddField(
            model_name='product',
            name='iiko_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='iiko UUID'),
        ),
        migrations.AddField(
            model_name='product',
            name='iiko_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
    ]
