# Generated by Django 6.0.3 on 2026-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_iiko_category_product_iiko_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iiko_sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Артикул iiko (num)'),
        ),
    ]
