# Generated by Django 6.0.3 on 2026-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product_iiko_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='IikoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Время синхронизации')),
                ('created_count', models.IntegerField(default=0, verbose_name='Создано')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Обновлено')),
                ('deleted_count', models.IntegerField(default=0, verbose_name='Удалено')),
                ('has_errors', models.BooleanField(default=False, verbose_name='Были ошибки')),
            ],
            options={
                'verbose_name': 'Лог синхронизации iiko',
                'verbose_name_plural': 'Логи синхронизаций iiko',
                'ordering': ['-synced_at'],
            },
        ),
    ]
