# Generated by Django 6.0.3 on 2026-04-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_iikosynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, default='🍽️', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rationslot',
            options={'ordering': ['order', 'meal_time__order'], 'verbose_name': 'Слот рациона', 'verbose_name_plural': 'Слоты рациона'},
        ),
        migrations.RemoveField(
            model_name='rationtemplateslot',
            name='slot_type',
        ),
        migrations.AlterField(
            model_name='rationslot',
            name='slot_type',
            field=models.CharField(blank=True, choices=[('breakfast_250', 'Завтрак 250–350 ккал'), ('breakfast_400', 'Завтрак 400–500 ккал'), ('second_400', 'Второе 400–500 ккал'), ('second_500', 'Второе 500–600 ккал'), ('soup_200', 'Суп 200 ккал'), ('soup_300', 'Суп 300 ккал'), ('salad_150', 'Салат 150–250 ккал'), ('salad_250', 'Салат 250–350 ккал'), ('dessert_100', 'Выпечка/Десерт 100–250 ккал'), ('dessert_300', 'Выпечка/Десерт 300–350 ккал'), ('smoothie', 'Смузи 100–150 ккал'), ('sandwich', 'Сэндвич 300–350 ккал')], max_length=50, null=True, verbose_name='Категория блюда'),
        ),
        migrations.AddField(
            model_name='rationslot',
            name='meal_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mealtime', verbose_name='Приём пищи'),
        ),
        migrations.AddField(
            model_name='rationtemplateslot',
            name='meal_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mealtime', verbose_name='Приём пищи'),
        ),
    ]
