# Generated by Django 5.0.14 on 2026-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_mealtime_alter_rationslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
