# Generated by Django 5.0.14 on 2026-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ration',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Рацион', 'verbose_name_plural': 'Рационы'},
        ),
        migrations.AddField(
            model_name='ration',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
