# Generated by Django 5.0.14 on 2026-06-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_ration_options_ration_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название подгруппы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подгруппа на замену',
                'verbose_name_plural': 'Блюда на замену',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SwapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_items', to='myapp.product', verbose_name='Блюдо')),
                ('swap_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.swapgroup', verbose_name='Подгруппа')),
            ],
            options={
                'verbose_name': 'Позиция на замену',
                'verbose_name_plural': 'Позиции на замену',
                'ordering': ['order', 'id'],
            },
        ),
    ]
