# Generated by Django 5.0.14 on 2026-06-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_consolidate_meal_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RationNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal_category', models.IntegerField(choices=[(1200, '1200 ккал'), (1500, '1500 ккал'), (1800, '1800 ккал'), (2500, '2500 ккал')], unique=True, verbose_name='Категория калорийности')),
                ('kcal_min', models.PositiveIntegerField(verbose_name='Ккал — мин')),
                ('kcal_max', models.PositiveIntegerField(verbose_name='Ккал — макс')),
                ('protein_min', models.PositiveIntegerField(verbose_name='Белки — мин, г')),
                ('protein_max', models.PositiveIntegerField(verbose_name='Белки — макс, г')),
                ('fat_min', models.PositiveIntegerField(verbose_name='Жиры — мин, г')),
                ('fat_max', models.PositiveIntegerField(verbose_name='Жиры — макс, г')),
                ('carbs_min', models.PositiveIntegerField(verbose_name='Углеводы — мин, г')),
                ('carbs_max', models.PositiveIntegerField(verbose_name='Углеводы — макс, г')),
            ],
            options={
                'verbose_name': 'Норма КБЖУ',
                'verbose_name_plural': 'Нормы КБЖУ',
                'ordering': ['kcal_category'],
            },
        ),
    ]
