# Generated by Django 5.0.14 on 2026-06-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_seed_ration_norms'),
    ]

    operations = [
        migrations.CreateModel(
            name='IikoCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iiko_name', models.CharField(max_length=300, unique=True, verbose_name='Название категории в iiko')),
                ('slot_key', models.CharField(choices=[('breakfast', 'Завтрак'), ('hot_400', 'Горячее 400-500'), ('hot_500', 'Горячее 500-600'), ('soup', 'Суп'), ('salad', 'Салат'), ('dessert', 'Выпечка/Десерт'), ('smoothie', 'Смузи'), ('sandwich', 'Сэндвичи')], max_length=50, verbose_name='Категория на сайте')),
            ],
            options={
                'verbose_name': 'Сопоставление категории iiko',
                'verbose_name_plural': 'Сопоставление категорий iiko',
                'ordering': ['iiko_name'],
            },
        ),
    ]
