# Generated by Django 5.0.14 on 2026-07-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_seed_iiko_pp_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='wishes',
            field=models.TextField(blank=True, null=True, verbose_name='Пожелания для Claude'),
        ),
    ]
