# Generated by Django 5.0.14 on 2026-07-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_ration_wishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeRationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа рационов Claude',
                'verbose_name_plural': 'Группы рационов Claude',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='ration',
            name='wishes',
        ),
        migrations.CreateModel(
            name='ClaudeRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название рациона')),
                ('kcal_category', models.IntegerField(choices=[(1200, '1200 ккал'), (1500, '1500 ккал'), (1800, '1800 ккал'), (2500, '2500 ккал')], verbose_name='Категория калорийности')),
                ('wishes', models.TextField(blank=True, null=True, verbose_name='Пожелания для Claude')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rations', to='myapp.clauderationgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Рацион Claude',
                'verbose_name_plural': 'Рационы Claude',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeRationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('hot_400', 'Горячее 400-500'), ('hot_500', 'Горячее 500-600'), ('soup', 'Суп'), ('salad', 'Салат'), ('dessert', 'Выпечка/Десерт'), ('smoothie', 'Смузи'), ('sandwich', 'Сэндвичи')], max_length=50, null=True, verbose_name='Категория блюда')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('meal_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mealtime', verbose_name='Приём пищи')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claude_ration_slots', to='myapp.product', verbose_name='Блюдо')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='myapp.clauderation', verbose_name='Рацион')),
            ],
            options={
                'verbose_name': 'Слот рациона Claude',
                'verbose_name_plural': 'Слоты рационов Claude',
                'ordering': ['order', 'meal_time__order'],
            },
        ),
    ]
