# Generated by Django 5.0.14 on 2026-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_clauderationgroup_remove_ration_wishes_clauderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clauderationslot',
            name='slot_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('hot_400', 'Горячее 400-500'), ('hot_500', 'Горячее 500-600'), ('soup', 'Суп'), ('salad', 'Салат'), ('dessert', 'Выпечка/Десерт'), ('smoothie', 'Смузи'), ('sandwich', 'Сэндвичи'), ('extra', 'Доп. товары')], max_length=50, null=True, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='iikocategorymap',
            name='slot_key',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('hot_400', 'Горячее 400-500'), ('hot_500', 'Горячее 500-600'), ('soup', 'Суп'), ('salad', 'Салат'), ('dessert', 'Выпечка/Десерт'), ('smoothie', 'Смузи'), ('sandwich', 'Сэндвичи'), ('extra', 'Доп. товары')], max_length=50, verbose_name='Категория на сайте'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='key',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('hot_400', 'Горячее 400-500'), ('hot_500', 'Горячее 500-600'), ('soup', 'Суп'), ('salad', 'Салат'), ('dessert', 'Выпечка/Десерт'), ('smoothie', 'Смузи'), ('sandwich', 'Сэндвичи'), ('extra', 'Доп. товары')], max_length=50, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='rationslot',
            name='slot_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('hot_400', 'Горячее 400-500'), ('hot_500', 'Горячее 500-600'), ('soup', 'Суп'), ('salad', 'Салат'), ('dessert', 'Выпечка/Десерт'), ('smoothie', 'Смузи'), ('sandwich', 'Сэндвичи'), ('extra', 'Доп. товары')], max_length=50, null=True, verbose_name='Категория блюда'),
        ),
    ]
