# Generated by Django 5.0.14 on 2026-07-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_readers_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kcal', models.PositiveIntegerField(unique=True, verbose_name='Калорийность, ккал')),
                ('kcal_tolerance', models.PositiveIntegerField(default=50, verbose_name='Погрешность ккал, ±')),
                ('protein', models.PositiveIntegerField(default=0, verbose_name='Белки, г')),
                ('protein_tolerance', models.PositiveIntegerField(default=5, verbose_name='Погрешность белков, ±г')),
                ('fat', models.PositiveIntegerField(default=0, verbose_name='Жиры, г')),
                ('fat_tolerance', models.PositiveIntegerField(default=5, verbose_name='Погрешность жиров, ±г')),
                ('carbs', models.PositiveIntegerField(default=0, verbose_name='Углеводы, г')),
                ('carbs_tolerance', models.PositiveIntegerField(default=10, verbose_name='Погрешность углеводов, ±г')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Калораж',
                'verbose_name_plural': 'Калоражи',
                'ordering': ['order', 'kcal'],
            },
        ),
        migrations.CreateModel(
            name='CalorieCategoryMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='myapp.caloriecategory', verbose_name='Калораж')),
                ('meal_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_meals', to='myapp.mealtime', verbose_name='Приём пищи')),
            ],
            options={
                'verbose_name': 'Приём пищи калоража',
                'verbose_name_plural': 'Приёмы пищи калоража',
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'meal_time')},
            },
        ),
    ]
