# Generated by Django 5.0.14 on 2026-07-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_migrate_calorie_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RationNorm',
        ),
        migrations.RemoveField(
            model_name='rationtemplateslot',
            name='template',
        ),
        migrations.RemoveField(
            model_name='rationtemplateslot',
            name='meal_time',
        ),
        migrations.AlterField(
            model_name='clauderation',
            name='kcal_category',
            field=models.IntegerField(verbose_name='Категория калорийности'),
        ),
        migrations.AlterField(
            model_name='ration',
            name='kcal_category',
            field=models.IntegerField(verbose_name='Категория калорийности'),
        ),
        migrations.DeleteModel(
            name='RationTemplate',
        ),
        migrations.DeleteModel(
            name='RationTemplateSlot',
        ),
    ]
