# Generated by Django 5.0.14 on 2026-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_calorie_ranges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, default='', max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('unit', models.CharField(default='1 шт', max_length=50, verbose_name='Кратность заказа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
