# Generated by Django 5.0.14 on 2026-08-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_seed_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price_manual',
            field=models.BooleanField(default=False, verbose_name='Цена задана вручную'),
        ),
    ]
