# Generated by Django 5.0.14 on 2026-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_seed_auto_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition_clean',
            field=models.TextField(blank=True, default='', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав (из iiko)'),
        ),
    ]
