# Generated by Django 5.0.14 on 2026-08-17 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_fill_composition_clean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_prices', models.BooleanField(default=False, help_text='Читатель сможет вносить «Цену прод.» в каталоге. Остальное останется только для чтения.', verbose_name='Может менять цены продажи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Права пользователя',
                'verbose_name_plural': 'Права пользователей',
            },
        ),
    ]
